### ISSUE TITLE
Create vagrant setup for hacking on Mote

### ISSUE THREAD

**Issue by ryanlerch** [fedora-infra/mote#104]
It would be awesome to have a stock Vagrant setup for hacking on the Mote interface.

This would make it easier for new contributors to jump in and hack.

**Comment by cydrobolt** [comment]
Hmm, what are some benefits of vagrant for this use case? I've found `vagrant` very helpful for more complicated stacks, but for mote, it seems like `virtualenv` could do the job well without the bulk of vagrant. i.e no database, Python, no real system dependencies otherwise

What do you think?

**Comment by jwflory** [comment]
Four years have passed on this issue. I think we could explore a container-native way of setting up a testing environment, or use virtual environments if that works too.

Closing as `wontfix`.
