### ISSUE TITLE
RFE: Ability to merge teams

### ISSUE THREAD

**Issue by mairin** [fedora-infra/mote#105]
Sometimes we title Fedora Design Team meetings 'fedora-design' and sometimes we title them 'design-team.' Is there a way we could merge these two 'teams' in m0te so they show up under one page? Right now they show up under different pages kind of randomly (as we use the meeting names kind of randomly.)

eg
https://meetbot.fedoraproject.org/sresults/?group_id=fedora-design&type=team
https://meetbot.fedoraproject.org/sresults/?group_id=design-team&type=team

**Comment by cydrobolt** [comment]
See #79
I've been a bit MIA recently, but I'll be working on it soon.

**Comment by mairin** [comment]
Oh thank you!
