### ISSUE TITLE
Group types are confusing

### ISSUE THREAD

**Issue by mairin** [fedora-infra/mote#106]
It's confusing when you're looking for a team in m0te and you get the team's IRC channel as one group and the actual team as another group. It's easy to gloss over / not notice the 'type' text field and assume you're getting two results for the same thing:
 
![screenshot from 2016-11-02 15-32-48](https://cloud.githubusercontent.com/assets/799683/19944312/ae2de936-a111-11e6-97cf-623ecfe08bf3.png)

One suggestion to make this less confusing would be to mark the group's type with an icon, which at a glance could make it clear - especially if it's right next to the group name - what type of group it is more easily than a separate text field:

![bitmap](https://cloud.githubusercontent.com/assets/799683/19944452/5f8e91a8-a112-11e6-8fc7-5978b6dc31a6.png)

It would also make sense to continue this scheme on the group details pages, eg to carry the icon over to pages like this:
https://meetbot.fedoraproject.org/sresults/?group_id=fedora-design&type=team

The icons used in the quick mockup above are from Font Awesome - 
- team - 'users'
- channel - 'comments'

**Comment by cydrobolt** [comment]
This is a really good idea! Thanks :)
