### ISSUE TITLE
Years listed in descending order but months in ascending order

### ISSUE THREAD

**Issue by mairin** [fedora-infra/mote#109]
Hi!
One little niggle with the UI for viewing a team's list of meeting minutes - the years are stacked most recent to least recent, with 2016 on the top. However, the months are least recent to most recent order - so if it's dec 2016, you have to scroll way down to view the notes for the month even tho it's the current month. I'd suggest flipping the months so the most recent month is always at the top; then the list will consistently display most recent notes at the top and least at the bottom. Right now it's out of order bc of the month order.

**Comment by cydrobolt** [comment]
I agree! This does seem odd. Will take a look.
