### ISSUE TITLE
Send email to appropriate mailing lists after each meeting

### ISSUE THREAD

**Issue by Cydrobolt** [fedora-infra/mote#11]
Send emails to the correct project mailing lists after mote receives a `fedmsg` "meeting ended" message, in order to encourage consistency and ensure the mailing list subscribers are kept up to date. `pkovar` from the Docs team suggested this to be added. 

We can hook into the `fedmsg` bus to learn when meetings end, and use the JSON/YAML configuration files to determine which email the meeting logs should be sent to.

**Comment by ralphbean** [comment]
This is probably a better fit for [fmn](https://apps.fedoraproject.org/notifications).  See fedora-infra/fmn#72, for example.

**Comment by Cydrobolt** [comment]
Yes, this does sound like a good idea for fmn!

**Comment by ralphbean** [comment]
Hey, so, since this is FMN's responsibility, I'm just going to close this issue.
