### ISSUE TITLE
usability: nothing happens when you click on a meeting date

### ISSUE THREAD

**Issue by skierpage** [fedora-infra/mote#112]
Visit a long-standing meeting like https://meetbot.fedoraproject.org/sresults/?group_id=kde-sig&type=team and click a date near the top such as 2016 > January > 2016-01-19.

Result: the date highlights in blue, but it seems nothing else happens.

Actually way down the page a "Minutes and Logs" section appears with links to minutes and logs, but it's easy to miss.

On click the page could scroll down to the `#minlogs` fragment ID. But since the years and months open nested, I think the Meetings and Logs for a date should open nested within it as well.

**Comment by cydrobolt** [comment]
Are you encountering this issue on mobile? On larger screens, the links to minutes and logs should appear in the column to the side. This leaves more space for logs and minutes to appear.

**Comment by skierpage** [comment]
> On larger screens, the links to minutes and logs should appear in the column to the side.
In Firefox Nightly 53 on Fedora 25, in a window half my HD screen wide (960 pixels) there's no column to the side... aha! it appears around 994 pixels wide.
a) you could show that column at much narrower window widths.
b) you should use some "scroll into view if not visible" command that's a no-op in two-column mode but jumps down to Minutes and Logs in single-column mode.
Thanks for the fast response!

**Comment by cydrobolt** [comment]
Hmm, that's a good idea. I definitely think that it could be hard to realize on small non-mobile screens that scrolling down is required to see the logs :)

Maybe triggering a scroll to the log section of the page could be useful!

**Comment by sashreek1** [comment]
Hey! I would like to work on this issue

I can try most of the possible solutions mentioned here and see which one works best. I'll get back to you once I am done with that. would that be fine ?

**Comment by jwflory** [comment]
@sashreek1 Hi, thanks for your interest! :tada: It might be a good idea to double-check if this is still an issue. Three years have passed since the last discussion here, so it is possible some things have changed since then.

**Comment by sashreek1** [comment]
Yes i did check and the issue does still exist :)

**Comment by jwflory** [comment]
@sashreek1 OK, great. Then yes, please go ahead and feel free to work on this. :tada: Drop a comment here if you have any questions or need feedback before making a Pull Request.
