### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by t0xic0der** [fedora-infra/mote#126]
In the spirit of getting more contributors to the project, the above document would be appreciated.

**Comment by antriksh123** [comment]
You can close this or review my pull request on CONTRIBUTING.md

**Comment by jwflory** [comment]
I think we need to work with a member of the Community Platform Engineering team on writing this document. There are things I do not know about CPE workflows and how to request reviews. So I think we should partner with someone who can answer the trickier questions about how to contribute here.

**Comment by t0xic0der** [comment]
> I think we need to work with a member of the Community Platform Engineering team on writing this document. There are things I do not know about CPE workflows and how to request reviews. So I think we should partner with someone who can answer the trickier questions about how to contribute here.

This stays open for now and I'll check if there is a mailing list for CPE. If so, I'll reach out to them to see if they can give some pointers regarding this.

**Comment by jwflory** [comment]
> This stays open for now and I'll check if there is a mailing list for CPE. If so, I'll reach out to them to see if they can give some pointers regarding this.

The Infra list is the best place to go for that. :grin: https://lists.fedorahosted.org/archives/list/infrastructure@lists.fedoraproject.org/

**Comment by jwflory** [comment]
_Discussed in [2020-10-25 meeting](https://youtu.be/gpLPDgYRIvA)_.

---

I am taking a first attempt at this. I plan to split off the developer environment section in the README into the CONTRIBUTING doc. From there, it should be easier to on-board new developers who want to work on a Flask project.

Together with @ramyaparimi, we will tag-team this in the second half of the sprint to make sure it is accurate and makes sense from different viewpoints. This should be complete by the end of the sprint on Sunday, 8 November, 2020.

**Comment by Ank221199** [comment]
Hey, I would like to take up this issue

**Comment by t0xic0der** [comment]
Done.
