### ISSUE TITLE
Add CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by t0xic0der** [fedora-infra/mote#127]
In the spirit of getting more contributors to the project, the above document would be appreciated.

**Comment by jwflory** [comment]
Reposting from PR #130:

> Hi! Actually, we cannot add this because we need to use the Fedora Code of Conduct. It is also under revision, to be shared later in 2020.
> 
> Let's revisit a Code of Conduct for the Fedora Infra GitHub repos later this year. It is important work, but it will quickly become outdated. I think it is better to send people looking for a Code of Conduct instead of giving them the wrong one. :slightly_smiling_face:

**Comment by jwflory** [comment]
For the above-mentioned reason, I am going to close this issue. I do think this is important, but we can revisit once there is more details on the Fedora CoC update. I am following this process actively so I should be able to follow up once there is new progress.
