### ISSUE TITLE
Persist copyright footer information in mobile view

### ISSUE THREAD

**Issue by t0xic0der** [fedora-infra/mote#128]
This is how it looks on the default desktop view.

![image](https://user-images.githubusercontent.com/49605954/94985631-f08cbd80-0575-11eb-9878-8b078bc8a2db.png)

And this is how it looks in the mobile view.

![image](https://user-images.githubusercontent.com/49605954/94985652-08644180-0576-11eb-9443-c82c5fb68d5d.png)

Slight changes to the media queries can facilitate showing up of the copyright footer even in the mobile view.

**Comment by jwflory** [comment]
Makes sense!

Also, thinking about this more… I think the license is actually incorrect for the content. The Møte logs do not fall under copyright, they fall under the [Current Default License](https://fedoraproject.org/wiki/Legal:Fedora_Project_Contributor_Agreement) for Fedora:

> "Current Default License", with respect to a Contribution, means (i)
> if the Contribution is Code, the MIT License, and (ii) if the
> Contribution is Content, CC-BY-SA supplemented by Moral Rights Clause
> Waiver and GPL Relicensing Permission.

**Comment by t0xic0der** [comment]
> I think the license is actually incorrect for the content. The Møte logs do not fall under copyright, they fall under the Current Default License for Fedora:

Welp. We can create another issue for that. :+1:

**Comment by jwflory** [comment]
PR #133 from @antriksh123 was merged and fixed this issue. Closing this issue as complete. :clapper:
