### ISSUE TITLE
[Subjective] Redundant links on the top bar

### ISSUE THREAD

**Issue by t0xic0der** [fedora-infra/mote#129]
![image](https://user-images.githubusercontent.com/49605954/94985737-b66feb80-0576-11eb-9ce9-18aa0be0ef30.png)

The `mote` link and the `home` link lead you to the same place. (Makes you think why to keep both when even one can suffice)

**Comment by chinmaym07** [comment]
Hey @t0xic0der Can I try this too ?

**Comment by Salim-Swaleh** [comment]
@t0xic0der Can I take on this issue please?
