### ISSUE TITLE
[User experience] Underutilized top menu bar

### ISSUE THREAD

**Issue by t0xic0der** [fedora-infra/mote#131]
The top bar looks like this.

![image](https://user-images.githubusercontent.com/49605954/94985808-46ae3080-0577-11eb-8549-6b4c3932f9d9.png)

This takes up a lot of screen real-estate with little utility. (Keeping in mind the redundancy of links as said in #129)

The search bar can head up there. 

![image](https://user-images.githubusercontent.com/49605954/94985885-c1774b80-0577-11eb-90d1-c9ebc92089d4.png)

Section titles can be accommodated there.

![image](https://user-images.githubusercontent.com/49605954/94985898-e23fa100-0577-11eb-8a04-60bf62fcd92e.png)

**Comment by antriksh123** [comment]
Could you be a bit more detailed as to what you are looking for?

**Comment by jwflory** [comment]
Not sure if section titles belong in the top menu bar. But I do really like the idea of adding the search bar there! I think search is the most utilized discoverability feature of Møte.

**Comment by chinmaym07** [comment]
Hey @t0xic0der  Can I try this ?
