### ISSUE TITLE
[Refactoring] Convert render returns to JSON returns for AJAX calls

### ISSUE THREAD

**Issue by t0xic0der** [fedora-infra/mote#136]
Certain operations can do without refreshing and rerendering the entire DOM, once an action has been performed. This can be done by introducing JavaScript codes which would make happen the request and receive a response from the server as a JSON-serializable object.

There are many places where this is needed so it is going to be a long haul.

- [ ] step 1
- [ ] step 2
- [ ] step 3

**Comment by t0xic0der** [comment]
Could you please assign me this @nasirhm? :hamburger:

**Comment by nasirhm** [comment]
Sure.

**Comment by t0xic0der** [comment]
This is a reminder comment for myself. I need to go through the template files provided in the template directory to understand which file needs work and which parts can be modernized into active AJAX calls.

**Comment by t0xic0der** [comment]
As the scope of this issue is quite huge and might span across multiple grounded issues, while this being a meta issue - like we discussed upon in the first developer meet; @ramyaparimi and @HiraTariq-01 can help down the line. :sweat_smile: This is something we would want to discuss about in the next meet @nasirhm @jwflory.

**Comment by jet2018** [comment]
Hello can I also work alongside @nasirhm on this, am confortable with JQuery AJAX calls and JQuery at large
