### ISSUE TITLE
A drop-in OrderedDict is needed for EPEL 6

### ISSUE THREAD

**Issue by Cydrobolt** [fedora-infra/mote#14]
Python 2.6 does not support collections.OrderedDict -- a drop-in is needed. 

Such a module can be found here: https://pypi.python.org/pypi/ordereddict
Fedora Package (supports EPEL 6): https://admin.fedoraproject.org/pkgdb/package/python-ordereddict/

This module needs to be implemented in mote's EPEL 6 builds.

**Comment by pypingou** [comment]
Do you target EL6 or EL7? (Fedora infra being moved to EL7)

**Comment by Cydrobolt** [comment]
Both, although the EPEL 6 build is not working because of this issue. 
The EPEL 7 build should be able to work correctly in its current state. `value01`, the server where mote needs to be run, is currently on EL6, but is getting moved to EL7 someday, not sure when yet.

**Comment by ralphbean** [comment]
Fun fact!  @nirik upgraded value01 from EL6 to EL7, so we don't strictly need to support EL6 anymore, at least not for fedora infrastructure.

If that's okay, then we can probably just close this issue as ``WONTFIX``.

**Comment by Cydrobolt** [comment]
Cool.
