### ISSUE TITLE
[Bug] : config.json while memcached being False

### ISSUE THREAD

**Issue by nasirhm** [fedora-infra/mote#140]
While trying to run the Application with copying the `config.py` file to `mote/` , It runs the application along with attaching a debugger to the WSGI application.

While accessing it via the browser, It was caused by the following issues (Stacktrace of the Debugger):
```
Traceback (most recent call last):
  File "/Infra/mote/mote/util.py", line 61, in get_json_cache
    with open(config().json_cache_location, mode='r') as json_store:
FileNotFoundError: [Errno 2] No such file or directory: '/var/cache/httpd/mote/cache.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Infra/mote/mote/__init__.py", line 98, in get_cache_data
    res = util.get_json_cache(meeting_type)
  File "/Infra/mote/mote/util.py", line 76, in get_json_cache
    raise RuntimeError("Cache not found.")
RuntimeError: Cache not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Infra/mote/mote/util.py", line 61, in get_json_cache
    with open(config().json_cache_location, mode='r') as json_store:
FileNotFoundError: [Errno 2] No such file or directory: '/var/cache/httpd/mote/cache.json'
```
Why are we storing the `cache.json` file in a root-level directory `/var/cache/httpd/cache.json` if we're using the `python runmote.py` to run the development build ?

**Comment by jwflory** [comment]
_Discussed in [2020-10-25 meeting](https://youtu.be/gpLPDgYRIvA)_.

---

This looks like some cruft still hanging in from when `memcached` was a more useful dependency. @nasirhm agreed to tackle this one for the current sprint, ending on Sunday, 8 November 2020. Will be completed after #138 is finalized.
