### ISSUE TITLE
Creation of Container Image

### ISSUE THREAD

**Issue by nasirhm** [fedora-infra/mote#142]
While migrating mote app to Python 3. 

For setting up the development environment, You have to install `memcached` and `pipenv` in your host machine.

It would be a good idea to containerize the app to run inside an isolated container with `podman` or `docker` in order to make sure, the developer doesn't have to install packages in their host machine.

**Path 1** : Do we want to go with a plain `Dockerfile` from which we can derive a container image and the developer can build it according to their changes and provide a `Makefile` with rules: `build` and `up` to ease the building and running process of containers with `podman` (if available) else `Docker`

The developer would have to do the following:
```
make new <- to build the container image everytime they modify stuff
make up <- run the built container image.
```

**Path 2**: Another path would be to use `docker-compose` or `podman-compose` with a `docker-compose.yml` file to create and run the container.

The developer would have to do the following:
```
docker-compose up <- to build and run the container
```

A feature for the compose path would be, It'll only recreate containers that have changed.

**Comment by jwflory** [comment]
_Discussed in [2020-10-25 meeting](https://youtu.be/gpLPDgYRIvA)_.

---

@t0xic0der volunteered to take this issue for the current sprint. Multi-container support is nice, so we agreed to use `docker-compose` while also rolling our own `Dockerfile` for møte itself. Depending on how the work goes with `memcached` (and whether we strip it out entirely), we may add other containers as dependencies for local development and testing.

For now, the `Dockerfile` and `docker-compose.yml` files are in-scope for this sprint, to be completed on Sunday, 8 November 2020.

**Comment by t0xic0der** [comment]
@nasirhm @jwflory What should be the base image for the image?

**Comment by nasirhm** [comment]
> @nasirhm @jwflory What should be the base image for the image?

I think, Python 3.x would work fine, What do you think @jwflory @t0xic0der ?

**Comment by t0xic0der** [comment]
The Python image on the hub is gigantic in size with multiple layers (None of which could be reused from the preexisting `ubuntu` or `fedora` images) while a `focal` image is hardly 72MB in size.

**Comment by t0xic0der** [comment]
Alpine it is. :smile:

**Comment by nasirhm** [comment]
> Alpine it is.

After researching a bit on it, using Alpine might not be a great idea for it, [here's why](https://pythonspeed.com/articles/alpine-docker-python/) . How about using `python:x.x-slim` ?

**Comment by jwflory** [comment]
_Discussed in [2020-11-01 sprint meeting](https://youtu.be/7l81smp61R8)_.

---

We reviewed what base image to use in the call today. We originally thought to use the Alpine Linux, but see @nasirhm's link above. For what it is worth, it is also common convention to use a base language image if you are mostly working in one stack only too.

**Comment by t0xic0der** [comment]
What is the outcome of this issue? An image, a docker file or both?

**Comment by nasirhm** [comment]
A `Dockerfile` that would result in a Image working fine with mapping port 5000 with host's 5000 would be a good starting point.
