### ISSUE TITLE
Determine final fate of memcached in Møte

### ISSUE THREAD

**Issue by jwflory** [fedora-infra/mote#148]
_Discussed in [2020-11-01 sprint meeting](https://youtu.be/7l81smp61R8)_.

---

# Summary

Determine whether memcached dependency is worth keeping in.

# Background

`memcached` is a dependency from the original project work, but after recent difficulties with running it locally, we are wondering how necessary it is. Fedora Infrastructure also retired their memcached service some time ago, so there is no longer an easy way of using this in production either.

In the sprint meeting where this issue came up, we noted that supporting memcached expands the scope for the Møte Modernization Project. We are most effective if we can focus on development. If we also need to run our own infrastructure and support a memcached deployment, that will take away valuable, limited time of the volunteer team to work on and improve Møte.

We need to make a final decision in the coming sprint for whether we strip it out of the project, or whether we explore ways to better integrate and/or find a new way to run this dependency both for development and production.

# Details

There are two options to move forward. @t0xic0der and @nasirhm are tag-teaming this one and will come back with a recommendation for the team by 22 November.

### Keep memcached

1. Better document and support running memcached for local development (preferably with containers)
1. See if we can request an [Amazon ElastiCache service](https://aws.amazon.com/elasticache/memcached/) from CPE Team to run memcached in production
1. Explore other edge cases once we get it running consistently

### Drop memcached

1. Remove unnecessary user-facing config options for memcached.
1. Clean up any Møte code that has strong reliance on memcached, if any

# Outcome

* Less friction for local development with difficult-to-test dependencies
* Think ahead for the future, once we get to a point where we are ready to deploy

**Comment by nasirhm** [comment]
_Discussed in [2020-11-08 sprint meeting](https://youtu.be/dJ995Zl2EH4)_.

---

It was suggested to keep `memcached` in the codebase for legacy and future purposes.
 
For development, to prefer the usage of file based cache would be better idea.
