### ISSUE TITLE
Adding README contents on the Sphinx documentation.

### ISSUE THREAD

**Issue by nasirhm** [fedora-infra/mote#152]
Adding basic setup documentation from README.md to Sphinx.

**Comment by nasirhm** [comment]
@HiraTariq-01 is working on it.

**Comment by HiraTariq-01** [comment]
> @HiraTariq-01 is working on it.

Will work on it, thank you!

**Comment by nasirhm** [comment]
@HiraTariq-01 as the PR https://github.com/fedora-infra/mote/pull/145 is merged. 

I think, we can work on adding contents from README to Sphinx Docs :D
