### ISSUE TITLE
Fix Travis Badge in Readme.md

### ISSUE THREAD

**Issue by nasirhm** [fedora-infra/mote#157]
Currently, In README.md, we have the Travis CI Badge Image, which seems to be broken.

Replace it with following lines:
```
[![Build Status](https://travis-ci.org/fedora-infra/mote.svg?branch=master)](https://travis-ci.org/fedora-infra/mote)
```
As It'll point to the Continuous Integration status for the `master` branch.

Currently, It says error:
![Screenshot from 2020-12-11 18-09-21](https://user-images.githubusercontent.com/35005234/101907206-0b198d80-3bdc-11eb-974d-81d5ec414ae8.png)

After the change, It'll point to either Passing or Failing of the `master` branch.

**Comment by nasirhm** [comment]
@HiraTariq-01 would you like to work on it ?

**Comment by gg-dev-05** [comment]
May I work on this issue?

**Comment by nasirhm** [comment]
Sure, Assigning it to you.

**Comment by nasirhm** [comment]
Meged: https://github.com/fedora-infra/mote/pull/158
