### ISSUE TITLE
Rework the design with faint gray gradient to fit with Fedora aesthetics

### ISSUE THREAD

**Issue by t0xic0der** [fedora-infra/mote#171]
For instance

![1](https://user-images.githubusercontent.com/49605954/131433323-42e745b5-f24c-4139-ab2c-8550aca52fc9.png)

**Comment by X3NOSAURUS** [comment]
Hey, I'd like to work on this?

**Comment by tuba-mouqeem** [comment]
Hey, can I work on this issue?

**Comment by t0xic0der** [comment]
Sure @tuba-mouqeem, can I have an ETA before I assign you this ticket?

**Comment by tuba-mouqeem** [comment]
2 days, it will be fine?

**Comment by tuba-mouqeem** [comment]
@t0xic0der please help me also setting up an environment. I am looking for HTML file that contains this main page code 
![image](https://user-images.githubusercontent.com/76019991/136712528-af962d00-1c51-404c-8473-3a4c82e71492.png)
but it has only two HTML pages
![image](https://user-images.githubusercontent.com/76019991/136712573-774363ab-fccf-456c-aa0b-43b3a5bef0e2.png) 
![image](https://user-images.githubusercontent.com/76019991/136712621-0fb63890-26ee-42fe-a47d-2bbf47b3ea89.png)
cloned file:
![image](https://user-images.githubusercontent.com/76019991/136712659-8ebafe5c-08c2-468a-adde-001cbf3ebfe4.png)

**Comment by tuba-mouqeem** [comment]
Thanks, I have set up

**Comment by tuba-mouqeem** [comment]
![image](https://user-images.githubusercontent.com/76019991/136848071-e2404ca0-123c-4740-a4cf-c94a6d7e5de4.png)

**Comment by tuba-mouqeem** [comment]
![image](https://user-images.githubusercontent.com/76019991/136853129-6b470196-825f-418f-a322-4bc73ec19b11.png)

**Comment by tuba-mouqeem** [comment]
Thank you, I have successfully started mote server
![image](https://user-images.githubusercontent.com/76019991/136918944-1314d548-99cd-4943-ba90-96a197aad2fe.png)
but still, CSS is not showing and I am having mote.main (lazy loading). I researched on the internet but not getting my answer 
![image](https://user-images.githubusercontent.com/76019991/136919528-12deb0c8-a2a6-4b00-bf02-d0c3c6a3b47d.png)

**Comment by t0xic0der** [comment]
> @t0xic0der can I work with @tuba-mouqeem on this

@jet2018, I don't have a problem with that as long as the task gets done satisfactorily. You would want to seek out to @tuba-mouqeem's permission in order to work together on this as she's the assignee for this ticket.

> @t0xic0der Sorry for taking more time I was setting up my Linux OS, I am done with the work.

No worries, I'll begin taking a look and reviewing it shortly.

**Comment by tuba-mouqeem** [comment]
@jet2018 Yes you can work with me

**Comment by t0xic0der** [comment]
Closed via https://github.com/fedora-infra/mote/pull/199

Nice work, @tuba-mouqeem!
