### ISSUE TITLE
Decentralize the configuration as an environment file

### ISSUE THREAD

**Issue by t0xic0der** [fedora-infra/mote#180]
Decentralize the configuration as an environment file

UPDATE - That environment file should be in the form of a config module, say `config.py`.

**Comment by DiptoChakrabarty** [comment]
I am interested in this issue , just wanted to know by decentralise you mean to put such variables in a .env right?
https://github.com/fedora-infra/mote/blob/7fca9434c1445b1108e532d1f1631baf7eef541a/modules/late.py#L31-L32

**Comment by t0xic0der** [comment]
Exactly.

We have a lot of variables like this one that we'd like to move away to an environment variable file.

**Comment by subhangi2731** [comment]
@t0xic0der @darknao With reference to the discussion in Element, can I please be assigned this issue now, so that I can start working?
