### ISSUE TITLE
Listen on the fedmsg bus to update memcached when a new meeting ends

### ISSUE THREAD

**Issue by Cydrobolt** [fedora-infra/mote#2]

**Comment by ralphbean** [comment]
Or, do it in real-time with fedmsg!

**Comment by Cydrobolt** [comment]
:+1:! Interesting :)
Is there a message that is sent every time a new meeting finishes? If not, mote could monitor the log folder and send the fedmsgs itself

**Comment by ralphbean** [comment]
> Is there a message that is sent every time a new meeting finishes?

There is.  [See here](https://apps.fedoraproject.org/datagrepper/raw?topic=org.fedoraproject.prod.meetbot.meeting.complete)

**Comment by Cydrobolt** [comment]
Exactly what I was looking for! Thanks!
