### ISSUE TITLE
Serve all static resources ourselves

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/mote#20]
Take a look at my network tab when viewing the staging mote instance:

![mote-resources](https://cloud.githubusercontent.com/assets/331338/8132994/7b993f7a-10f3-11e5-991d-ff60b967b847.png)

Some of them are coming from gstatic.com, some from googleapis.com, some from bootstrapcdn.com, etc..  We can't have that on a Fedora Infrastructure app, mostly for privacy issues.  We don't want to be redirecting our users off-site for resources so that their web activity can be secretly monitored by other entities.  Trust me.. people will complain.

We only allow this for a limited number of off-site services (like libravatar.org, for instance).

**Comment by Cydrobolt** [comment]
Yup, we actually used the FontAwesome CDN because nirik suggested that an external CDN might help circumvent the lack of fontawesome in EPEL 6. However, since value01 is now on el7, we should be able to move it back.

**Comment by pypingou** [comment]
So what is the status of this ticket?

**Comment by cydrobolt** [comment]
Most of the offsite resources have been fixed, but some embedded Google fonts in the bootstrap style sheet might still be present.

**Comment by jwflory** [comment]
Hi! So, a 4-5 year follow-up here. So, as @cydrobolt commented above, most off-site resources were already moved to be served locally. I don't think it is that unconventional to serve fonts externally. And if it does bother people, I would like someone to come forward and open a new issue, and we can address it then.

So, I am closing this one as complete. :clapper:
