### ISSUE TITLE
Change position of channel hyperlink on topbar

### ISSUE THREAD

**Issue by subhangi2731** [fedora-infra/mote#206]
The position of `channel` hyperlink in the topbar is uneven in comparison to that of the `Fragment` logo. It can either be brought a little down to make it even or can removed to the right beside the `Get fedora` link.

![Screenshot from 2021-11-01 23-55-58](https://user-images.githubusercontent.com/53938490/139722606-5cd95041-8baf-4f41-87a8-778138b0da58.png)

Also, is `Channel` hyperlink on the topbar necessary, when the same functionality is achieved through the `Explore` section? Could you please elaborate @darknao @t0xic0der

**Comment by subhangi2731** [comment]
@darknao @t0xic0der

**Comment by subhangi2731** [comment]
If this issue is relevant I would like to work on this issue so please assign me

**Comment by t0xic0der** [comment]
@subhangi2731, sure. Assigning this issue to you.

**Comment by subhangi2731** [comment]
@t0xic0der Should the channel hyperlink be made even(brought a little down), or moved to the right beside `Get Fedora` link?

**Comment by darknao** [comment]
I think we should either remove it completely, or brings all others major functionalities up there too (search & recent meetings).
I personally prefer the first option.
If we decide to keep it, it should stay on the left side, but make it aligned with the `Fragment` logo.
Note that `Get Fedora` is not aligned either.

**Comment by t0xic0der** [comment]
Closed via #207. Thanks for working on this, @subhangi2731.
