### ISSUE TITLE
Fixing footer

### ISSUE THREAD

**Issue by kedar-hargude** [fedora-infra/mote#209]
Correcting the links in footer.

**Comment by kedar-hargude** [comment]
@t0xic0der may you assign this to me?

**Comment by kedar-hargude** [comment]
@t0xic0der @darknao Since we also want to show the names of the project contributors through the footer link, in a modal view, how should the names of contributors be fetched?

**Comment by kedar-hargude** [comment]
@t0xic0der @darknao May you please review and suggest changes

**Comment by oneamanish** [comment]
Hello ,
can you assign me for new codes!

**Comment by jet2018** [comment]
Hello can I also contribute on this?

**Comment by t0xic0der** [comment]
Closing this as FIXED.
