### ISSUE TITLE
Move teams JSON file to ansible.

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/mote#21]
That way:

- we don't rely directly github.com for startup.
- sysadmins can change it and push out a new copy.
- we don't have to cut a new release of the rpm just to change that teams definition

We'll want to keep a copy on github so people can easily make a PR for it.  But we should keep the primary copy in ansible, just like we do with the [apps.fp.o data](http://infrastructure.fedoraproject.org/cgit/ansible.git/tree/roles/apps-fp-o/files/apps.yaml).

**Comment by Cydrobolt** [comment]
:+1:

**Comment by Cydrobolt** [comment]
Fixed in def333749607a3e4dbe95e28f5bb27e255d79ba9
