### ISSUE TITLE
Rework the landing page

### ISSUE THREAD

**Issue by t0xic0der** [fedora-infra/mote#228]
With the significant amount of inputs we accrued from @mairin and @misc, I have a plan that can help rework the landing page in a way that it would end up feeling a lot usable and functional. 

![image](https://user-images.githubusercontent.com/49605954/144360372-f4fbf09a-d9d6-4c3b-8489-7350dd4939a7.png)

This illustration is not pixel-perfect and is representative of the relative positions of the elements that we would want to have on the landing page.

I guess some more context would help, so here's some more context ;P

1. The recent section would have a calendar display restricted to only on the month view as going any further, would defeat the purpose of calling it "recent".
2. The channels section would have a list of channels sorted by activity with a textual/graphical activity view at the right side of it. We'll have a button, that would lead to a modal having all the channels.
3. When the width is not enough for both of them to stick aside each other, these sections will stack - the recent section would be on the top while the channels section would be at the bottom.
4. We will move out the search bar from the lookup modal to the page with suggestive search mechanism that lists the top 5 results and then, provides an option to view the remaining results in a modal if the count is more than 5.
5. With so much activity on the landing page, we will have to get rid of the textual information that is present right now - but maybe we will move that to the about modal.

Opinions?

**Comment by mairin** [comment]
This is close to what I was thinking. Here's some higher fidelity mockups in case it helps
![Meetings by Group-1](https://user-images.githubusercontent.com/799683/144504408-0031c0d5-684b-4e41-ba25-93942719489c.png)
![Meetings by Group](https://user-images.githubusercontent.com/799683/144504409-a070e30a-13eb-481d-b8c1-deb5df51e585.png)
![Meetings By Date](https://user-images.githubusercontent.com/799683/144504410-e2e71b29-5cbe-4dfb-b3fe-283addc90680.png)

**Comment by t0xic0der** [comment]
Superb! Thank you so much, @mairin. These are definitely going to help a lot.

**Comment by subhangi2731** [comment]
@t0xic0der please assign me this issue as this is of high priority as of now
