### ISSUE TITLE
Unable to read any meeting logs

### ISSUE THREAD

**Issue by pnemade** [fedora-infra/mote#23]
Currently for any meeting log I see some dots animation appears which moves dots clockwise but nothing happens. After sometime I see message. This is happening for any meeting log

```Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at root@localhost to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.```

**Comment by Cydrobolt** [comment]
Can you please describe each step you took before encountering the error? We had an issue for a couple hours in the afternoon that could have caused a 500, but that was fixed a bit later. 

Can you try again and see if you can view logs? If not, please describe the steps you took to reproduce the error.

Thanks!

**Comment by pnemade** [comment]
I got this link on fudcon-planning list -> http://meetbot.fedoraproject.org/fedora-meeting/2015-06-13/fedora-meeting.2015-06-13-04.00.log.html

I tried this 2-3 times few hours ago but unable to open it. I just now tried this link and now there is simple but different message "The requested URL /fedora-meeting/2015-06-13/fedora-meeting.2015-06-13-04.00.log.html was not found on this server."

Then I tried this link http://meetbot.fedoraproject.org/fedora-meeting-2/2015-06-11/env-and-stacks.2015-06-11-17.00.log.html and this also failed.

**Comment by ralphbean** [comment]
This was my bad.  **Half** of the staging configuration for mote made it out to production, which ruined meetbot.fp.o links.  A couple patches to our ansible repo and it should be back to normal now.

- http://infrastructure.fedoraproject.org/cgit/ansible.git/commit/?id=3dff80920d6309ec110326acc7b2385c436a3e4a
- http://infrastructure.fedoraproject.org/cgit/ansible.git/commit/?id=0a7f7604e69b6852bd7f6927c85ec63961c8b50e

**Comment by Cydrobolt** [comment]
Ah. Thanks for the fix, @ralphbean
