### ISSUE TITLE
Bug with FAmSCo meetings

### ISSUE THREAD

**Issue by Cydrobolt** [fedora-infra/mote#25]
There is a bug with FAmSCo meetings, they seem to return an error. Perhaps someone accidentally edited one of the file names or file formats in a way that broke mote. This error is caused more specifically by a mislabled date. Maybe we can ignore the error, or show a link to the -raw.

**Comment by ralphbean** [comment]
Can you link to where you see the error @Cydrobolt?

**Comment by ralphbean** [comment]
Is it [here](http://meetbot.fedoraproject.org/sresults?group_id=famsco&type=team)?

**Comment by Cydrobolt** [comment]
@threebean yup.

**Comment by Cydrobolt** [comment]
The new time-based relevancy sorting formula seems to get stuck on this issue as well, hanging if "famsco"  is searched.
