### ISSUE TITLE
Setting remote URL as localhost breaks links

### ISSUE THREAD

**Issue by Cydrobolt** [fedora-infra/mote#26]
This seems to break certain links, such as links to "original" and text links that redirect directly to the "original" text files. 

We can probably fix this by having different remote linking and remote fetching URLs.

**Comment by apevec** [comment]
Please fix this, we need .txt for posting meeting minutes.

**Comment by Cydrobolt** [comment]
Can you use the.-raw link?
Just add "-raw" to MeetBot link like so.

http://meetbot-raw.fedoraproject.org/blablabla/bla.txt

**Comment by apevec** [comment]
Thanks, that worked!
It was just too much javascript for me, good to have static website as fallback :)

**Comment by Cydrobolt** [comment]
Fixed in 336ed16666515bf5b854982fc21f0f2e8c6aa5e7
