### ISSUE TITLE
Fetch single-log contents from channel first if available

### ISSUE THREAD

**Issue by pnemade** [fedora-infra/mote#27]
we finished g11n meeting in #fedora-meeting 1 hr ago but I am still not able to see the log url -> http://meetbot.fedoraproject.org/fedora-meeting/2015-06-17/g11n.2015-06-17-04.30.html

The error message is " Not Found

The requested URL /meetbot/teams/g11n/g11n.2015-06-17-04.30.log.html was not found on this server.
"

**Comment by pnemade** [comment]
I desperately need to check log files and provide particular reference from that log file in a ticket but its not working....

**Comment by pnemade** [comment]
after some discussion on #fedora-apps, I come to conclusion that only this g11n meeting log files are not working and all previous meeting logs are accessible.

**Comment by puiterwijk** [comment]
Note, for now we have http://meetbot-raw.fedoraproject.org/fedora-meeting/2015-06-17/g11n.2015-06-17-04.30.html

**Comment by Cydrobolt** [comment]
Yes, the raw link should work nonetheless. I've also noticed this error. It is due to the fact that `teams/` is on a cron task, and files underneath are not immediately available for viewing.

I will try to fix this issue soon by making sure the single-log viewer first pulls raw logs from fedora-meeting (channel) rather than `teams/`.

Another option would be to have whichever task the cron is running also get triggered by mote-updater.

**Comment by Cydrobolt** [comment]
Please give -raw a try for now (thanks @puiterwijk), the cron task should update soon and I will fix the fetching pattern to make sure all logs update immediately.

**Comment by pnemade** [comment]
Thanks @Cydrobolt but can you fix that g11n meeting link for now.

**Comment by Cydrobolt** [comment]
Could you change the link in the ticket to the raw link http://meetbot-raw.fedoraproject.org/fedora-meeting/2015-06-17/g11n.2015-06-17-04.30.html until we fix the issue?

**Comment by pnemade** [comment]
Okay no problem

**Comment by ralphbean** [comment]
I'm pretty sure #29 will fix this issue.

**Comment by Cydrobolt** [comment]
@pnemade the mote link should have synced itself. Closing ticket as #29 should fix the issue once we deploy it.
