### ISSUE TITLE
Please restore previous way of viewing meeting logs

### ISSUE THREAD

**Issue by pnemade** [fedora-infra/mote#28]
Previously I can go to any date like http://meetbot.fedoraproject.org/fedora-meeting/2015-06-17/ and browse what meetings happened on that day and read the logs without issue. 

Now the directory viewing is not allowed. Please allow it. The error I get with above URL is "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."

**Comment by puiterwijk** [comment]
For that you can use meetbot-raw: http://meetbot-raw.fedoraproject.org/fedora-meeting/2015-06-17/

**Comment by Cydrobolt** [comment]
You can get similar behavior by searching for "fedora-meeting" in the search box. This will bring you to the same result.


http://meetbot.fedoraproject.org/sresults?group_id=fedora-meeting&type=channel

**Comment by pypingou** [comment]
@Cydrobolt what about supporting these urls as search query?

This would avoid breaking existing URLs that could have been shared/bookmarked

**Comment by pnemade** [comment]
I am more interested to search by date rather than meeting channel name. Also, I assume the mote UI is still not complete right? I need to click few times before reaching particular meeting log. Previously its easy I can calculate if today is fesco meeting then last week same day I can browse and read the meeting log.

Also, I think in the past channels used to change meetings based on day-light saving time changes that results clashes with other meetings( from fedora-meeting to fedora-meeting1 or fedora-meeting2). So, instead of letting end user to know in advance which channel particular meeting happened, I find date based direct search more useful.

**Comment by ralphbean** [comment]
> I am more interested to search by date rather than meeting channel name.

Can you file an RFE for this indicating how you'd like it to work?

**Comment by Cydrobolt** [comment]
@pypingou yeah, that sounds like a good idea as well.
