### ISSUE TITLE
 As a fedora-infra member, I want to have mote's packaging automated.

### ISSUE THREAD

**Issue by StephenCoady** [fedora-infra/mote#284]
## Acceptance Criteria

* packit.yml is added to the project
* once added, we can successfully create released rpms for mote
* https://src.fedoraproject.org/rpms/mote is updated by packit

**Comment by t0xic0der** [comment]
Closing this as invalid as we have deprecated point-based versioned releases in favour of the continuous deployment of the application. As new features make it to the primary branch of the repository, they would be automatically deployed and hence, this does not need to be packaged - let alone automated for packaging.
