### ISSUE TITLE
RFE: Please if possible add date based search

### ISSUE THREAD

**Issue by pnemade** [fedora-infra/mote#36]
In the search form you can just add calendar and let user select any date and based on date selection, results should show all the meetings happened on that particular date in fedora channels.

I don't have specific use case for this but I also realized that when I used to search old meeting logs at meetbot-raw.fedoraproject.org, I actually search by channel name and then date which is already implemented in mote.

Maybe this RFE can be considered as one more way of querying meeting logs. Also, feel free to close this if developers think this kind of search is redundant as with using the graphical interface we definitely need to use some mouse clicks to reach particular log.

**Comment by Cydrobolt** [comment]
Additionally, as @pypingou pointed out, we could also catch URLs in the format of http://meetbot.fedoraproject.org/fedora-meeting/2015-06-17/

**Comment by ralphbean** [comment]
@Cydrobolt that would solve one half of it.. but the other half is trying to search for meetings by **just** date in **any** channel.  That's currently not possible in either the *old* interface or mote.

**Comment by Cydrobolt** [comment]
Oh, I see what he means. Hmm. We could definitely implement that as well.

**Comment by Cydrobolt** [comment]
#43 is relevant

**Comment by bexelbie** [comment]
Can we get a solution today to just list all meetings in reverse chronological order. I am routinely struggling to find meetings which I know happened because I don't know what semi-random meeting name was selected.

**Comment by cydrobolt** [comment]
@bexelbie Are you looking for the most recent meetings? There is a list of the most recent meetings on the front page. Additionally, if you know which channel the meeting occurred in (e.g #fedora-meeting, #fedora-meeting-2, etc), you can search for the channel and browse to the correct day to find the meeting you are looking for.

I would also suggest that you contact the group to help them choose better meeting names.

**Comment by bexelbie** [comment]
@cydrobolt I saw the list of most recent meetings, but it stops after only a few.  

Searching for a channel brings up a list I have to choose from, not a channel/date picker.

If we support these methods, it should be documented.

The browse screen seems to indicate only those specific meetings can be found.  Which is doubly frustrating when you know there are active groups who met yesterday who aren't listed.

**Comment by keszybz** [comment]
> In the search form you can just add calendar and let user select any date and based on date selection, results should show all the meetings happened on that particular date in fedora channels.

I think this is exactly what the new 2.0 version does: you have a calendar on the landing page, so you can just select any date and see all the meetings on that date.
