### ISSUE TITLE
As a prospective contributor, I want to quickly find the link to mote sources on meetbot.fp.o

### ISSUE THREAD

**Issue by sanjayankur31** [fedora-infra/mote#363]
I was looking around meetbot.fp.o for a link to the sources (here). I couldn't find one. Could one please be included in the footer, and maybe on the "about" page too?

**Comment by t0xic0der** [comment]
Thanks for letting us know, @sanjayankur31.
I will look into it.

Also as a side note, the narrative-based issue title is something that we [created](#284) as a part of the CPE initiative where we were [automating packaging for the Fedora Infrastructure apps](https://pagure.io/cpe/initiatives-proposal/issue/20) on GitHub using Packit. Therefore, it is not a regulated theme for issue titles so please totally free to simplify them :)
