### ISSUE TITLE
which link should be used?

### ISSUE THREAD

**Issue by alick** [fedora-infra/mote#45]
Hi, I find that recently that links like http://meetbot.fedoraproject.org/fedora-zh stop working, while http://meetbot.fedoraproject.org/meetbot/fedora-zh and http://meetbot-raw.fedoraproject.org/fedora-zh can still give out the list of all meetings by date. The last one seems new to me. I wonder which link is preferred for use?

Background: we use a customized python script (https://github.com/FZUG/ggmm) to generate meeting minutes email for the Fedora Chinese community.

**Comment by ralphbean** [comment]
If you have a script that is scraping the old interface, I recommend:  http://meetbot-raw.fedoraproject.org/fedora-zh

**Comment by ralphbean** [comment]
We put a new human interface (mote) over the logs and then moved the old "raw" logs to that meetbot-raw.fp.o url.  Let us know if it is problematic for you!

**Comment by Cydrobolt** [comment]
I recommend this:
http://meetbot.fedoraproject.org/sresults?group_id=fedora-zh&type=channel

**Comment by alick** [comment]
@ralphbean Thanks for the quick reply!
@Cydrobolt I guess it is more to human right?

**Comment by Cydrobolt** [comment]
@alick my link for humans, Ralph's link for bots :)
