### ISSUE TITLE
RFE: work around meetings that don't use #meetingname

### ISSUE THREAD

**Issue by cmurf** [fedora-infra/mote#46]
Fedora Server WG meetings do not use #meetingname, and therefore meetbot.fedoraproject.org doesn't know about its meetings, so meeting logs are (at the moment apparently) non-locatable unless you already know the complete URL I guess.

Reproduce steps:
1. http://meetbot.fedoraproject.org/
2. Browse: No working groups are listed, including Server.
3. Search field: typing in "server" brings up two results: server-wg and
fedora-server, neither of which have any 2015 entries.

https://lists.fedoraproject.org/pipermail/server/2015-July/001944.html

**Comment by Cydrobolt** [comment]
These meetings can still be locatable, in the same fashion that the meetings were locatable previously.
You can search for the channel (e.g "fedora-meeting") in the search bar, then navigate through date to find the correct meeting. What method did you use to find the meetings previously? Did you use channel and date like this?

**Comment by cmurf** [comment]
I didn't try this. It does work. I didn't consider it because the field asks for a group name, and I didn't consider the name of a channel as the same thing as a group name.

**Comment by Cydrobolt** [comment]
It accepts both channels or teams (#meetingname) :)

**Comment by Cydrobolt** [comment]
Closing the ticket for now, reopen if needed :)
