### ISSUE TITLE
Links in meeting minutes to full logs are wrong in modal view

### ISSUE THREAD

**Issue by mattdm** [fedora-infra/mote#53]
The meeting minutes have links to the full logs, both at the top and inline for various topics. These all result in 404 errors.

I think ideally they should go to that full log within møte.

**Comment by Cydrobolt** [comment]
Yes, we should use BeautifulSoup to replace those links ideally. Perhaps some kind of regex will also be needed.

**Comment by sanjayankur31** [comment]
I don't think this is an enhancement, it's more a defect at the time being. :/

Here are some more details: On this page: ​https://meetbot.fedoraproject.org/fedora-meeting/2015-09-02/workstation.2015-09-02-14.01.html/

"full logs" links to: ​https://meetbot.fedoraproject.org/fedora-meeting/2015-09-02/workstation.2015-09-02-14.01.html/workstation.2015-09-02-14.01.log.html

but the actual link, (as puiterwijk later informed me me) should be: ​https://meetbot-raw.fedoraproject.org/fedora-meeting/2015-09-02/workstation.2015-09-02-14.01.log.html

**Comment by Cydrobolt** [comment]
@sanjayankur31, the bug you are referring to is actually #60

**Comment by Cydrobolt** [comment]
Fixed in fa635fb0a137a74ffb7bafcd52c69e09ebc20360
