### ISSUE TITLE
No obvious way to get URL for specific minutes or logs to share from minutes/logs view

### ISSUE THREAD

**Issue by mattdm** [fedora-infra/mote#54]
When I click on a specific meeting, it is displayed as a pop-up in the same window. This is fine, but it'd be nice to have some way to open that in a window of its own, and to get a link to just that meeting to share.

**Comment by mattdm** [comment]
I know there are separate buttons for permalink, but it'd be nice to have that _without_ closing the view.

**Comment by Cydrobolt** [comment]
Hmm. What do you mean? Do you mean a permalink button from within the viewer modal?

**Comment by mattdm** [comment]
> Hmm. What do you mean? Do you mean a permalink button from within the viewer modal?

Yeah, something like that, exactly. :)

**Comment by Cydrobolt** [comment]
![image](https://cloud.githubusercontent.com/assets/1058150/9667430/bca291a0-5249-11e5-94fc-e78c8e79ae9b.png)
