### ISSUE TITLE
Reverse month, day, and meeting lists to be newest first.

### ISSUE THREAD

**Issue by mattdm** [fedora-infra/mote#55]
Right now, years are latest at the top, but months and the meetings within the month are in order. Usually, I'm looking for recent meetings (and probably most often, the latest meeting). The current UI makes that more buried than I'd like.

**Comment by Cydrobolt** [comment]
@mattdm I think this could also potentially be a discussion item. Some people may prefer that months/days are listed from lowest to highest (chronological order), and a reverse order may cause confusion -- however, I totally agree with you that most people are looking for the most recent meetings. 

I added a "Latest Meeting" button to help speed up the lookup process. @ralphbean any thoughts?

**Comment by jwflory** [comment]
I concur with @mattdm above. Marking this as a "good first issue".

**Comment by jwflory** [comment]
_Discussed in [2020-10-25 meeting](https://youtu.be/gpLPDgYRIvA)_.

---

We briefly discussed this one. @nasirhm is working on #138 and #140 this sprint. If @nasirhm happens to have spare time before 8 November, he may work on this one too. But we did not officially schedule it into this sprint.

**Comment by nasirhm** [comment]
It seems currently, we do get the latest meeting at the top along with the latest month and latest date at the top. 

It seems fixed :) 
 
![Uploading Screenshot from 2020-11-08 17-00-47.png…]()
