### ISSUE TITLE
RFE: show link to latest meeting for a given group immediately

### ISSUE THREAD

**Issue by mattdm** [fedora-infra/mote#56]
Usually, I am looking to find the most recent meeting for a given group. Let's optimize for this. On a given team page (like http://meetbot.fedoraproject.org/sresults/?group_id=council&type=team), either:

A. Have a block at the top of the page showing the links to the latest minutes (and possibly log)

or

B. Just have the latest year/month/meeting already expanded.

**Comment by Cydrobolt** [comment]
Will take a look at the RFEs/issues over the weekend ;)

**Comment by Cydrobolt** [comment]
@mattdm ^ should work :)
