### ISSUE TITLE
Fix links in full/permalink view with trailing slashes.

### ISSUE THREAD

**Issue by pnemade** [fedora-infra/mote#60]
I have observed that when clicked on full logs link on http://meetbot.fedoraproject.org/fedora-meeting/2015-08-05/fesco.2015-08-05-18.00.html navigates you to http://meetbot-raw.fedoraproject.org/fedora-meeting/2015-08-05/fesco.2015-08-05-18.00.html/fesco.2015-08-05-18.00.log.html

The correct URL should be http://meetbot-raw.fedoraproject.org/fedora-meeting/2015-08-05/fesco.2015-08-05-18.00.log.html

**Comment by Cydrobolt** [comment]
Hmm, you are correct. It looks like this bug is triggered by the trailing slash, causing the link to be incorrect.

**Comment by Cydrobolt** [comment]
a755ef0b1398ea09661e99eff42486df1bcfcbcb should fix the issue

**Comment by pnemade** [comment]
Is this fix deployed already? I used page https://meetbot.fedoraproject.org/fedora-meeting-1/2015-08-26/cloud_wg.2015-08-26-17.00.html and tried to open full log but it error with same problem as reported in this issue.

**Comment by Cydrobolt** [comment]
@pnemade, no,  we haven't deployed yet
