### ISSUE TITLE
Catch meetbot.fp.o requests with a Flask pattern

### ISSUE THREAD

**Issue by Cydrobolt** [fedora-infra/mote#7]
"original" logs will need to be moved to another domain, such as `meetbot-store.fp.o`, while `meetbot.fp.o` requests can be simply caught by mote.

**Comment by pypingou** [comment]
Shouldn't it be the other way around to avoid breaking all existing links?

**Comment by Cydrobolt** [comment]
@pypingou can you elaborate? Existing links should still work fine, as mote should be able to capture these URLs and serve the correct logs/minutes.

**Comment by Cydrobolt** [comment]
Added in d6e5dae753b847993c33b3f30972e250dcccd2d1
