### ISSUE TITLE
run_tests.sh script does not install for dependencies

### ISSUE THREAD

**Issue by jflory7** [fedora-infra/mote#73]
When trying to test local changes of møte, the `run_tests.sh` script fails with the following stacktrace.
```
./run_tests.sh 
 Setting up test environment...
 Running nosetests...
./run_tests.sh: line 55: nosetests: command not found
 Cleaning up...
```
Running `dnf provides nosetests` provides no results. Not sure if this is a typo for another command or if it's a package that needs to be installed for the script to work as expected.

**Comment by cydrobolt** [comment]
Right. You need to install the dependencies before you can run the tests. 

Try this: `pip install -r requirements.txt`

For future reference, `nose` is provided by `pip`: `pip install nose`
