### ISSUE TITLE
New line break for categories with more than one meeting

### ISSUE THREAD

**Issue by jflory7** [fedora-infra/mote#75]
When browsing through the møte directory listing, categories with more than one meeting listed under them are clumped together without any kind of distinct separation. It is unclear that there is more than one meeting for a category currently.

I think the best method of separating them is by a line break for each new type of meeting in a category. This will make them easier to see as their own standalone meeting type.

**Comment by cydrobolt** [comment]
This was fixed in 02e4e01e60ede78c7bf47daa58959126b2ab0a3c, but we haven't deployed this yet.
