### ISSUE TITLE
404 nick links in the meeting minutes

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/mote#80]
https://meetbot.fedoraproject.org/sresults/?group_id=infrastructure&type=team
Clicking on `nirik` takes me to https://meetbot.fedoraproject.org/sresults/infrastructure.2016-02-04-18.00.log.html#l-6

**Comment by cydrobolt** [comment]
Hm, right. The relative URLs don't map correctly when used in the modal view. We should generate an absolute path for these links to ensure that they work in the modal as well.

**Comment by kedar-hargude** [comment]
@fedora-infra-bot @t0xic0der Is this issue still required?

**Comment by kedar-hargude** [comment]
Hey @lmacken , Is this issue still required?
