### ISSUE TITLE
Line anchors don't work properly

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/mote#81]
So each line has an `l-<num>` anchor name, but a link like https://meetbot.fedoraproject.org/teams/infrastructure/infrastructure.2016-02-04-18.00.log.html#l-100 doesn't work properly unless I press enter on the URL after the page has initially rendered. It would be nice to be able to link directly to any line (or group of lines).

**Comment by cydrobolt** [comment]
Thanks for reporting this! I noticed this before, but never filed an issue for it. Since mote loads logs dynamically, after the page loads, the line anchors don't work initially. 

I'll fix this issue by performing the scroll after the entire log loads. :+1:

**Comment by rdp1070** [comment]
Hey, I think I can fix this, and since it's 16 days old I am going to assume no one is working on it. 
I will submit a PR as soon.

**Comment by cydrobolt** [comment]
@rdp1070 great, thanks! :+1:

**Comment by rdp1070** [comment]
I have created a pull request for this issue.

**Comment by cydrobolt** [comment]
Fixed in #88 and 6f63adea3ad7b4a35dbced91379198c4dd9ef467
