### ISSUE TITLE
Latest release not in rawhide

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/mote#93]
If we're updating F23 and EPEL, we should definitely be updating rawhide and F24 also to avoid upgradepath issues.

https://bugzilla.redhat.com/show_bug.cgi?id=1311337

```
~❯ pkgwat releases mote
+---------------+-----------------------+-----------------+
| release       | stable_version        | testing_version |
+---------------+-----------------------+-----------------+
| Rawhide       | 0.4.3-3.fc24          | None            |
| Fedora 24     | 0.4.3-3.fc24          | None            |
| Fedora 23     | 0.5.1-3.fc23 (update) | None            |
| Fedora 22     | 0.4.1-2.fc22 (update) | None            |
| Fedora EPEL 7 | 0.5.1-3.el7           | None            |
| Fedora EPEL 6 | None                  | None            |
| Fedora EPEL 5 | None                  | None            |
+---------------+-----------------------+-----------------+
```

**Comment by cydrobolt** [comment]
@ralphbean I thought rawhide automatically rebuilt -- should I `fedpkg build` in the master branch?

**Comment by ralphbean** [comment]
Yes - that'll do it :)

rawhide gets automatically pushed to a repo after you build it.  For stable branches you have to do bodhi updates - for rawhide you do not... but you still have to build it.

**Comment by cydrobolt** [comment]
I rebuilt `mote` in rawhide

http://koji.fedoraproject.org/koji/buildinfo?buildID=751072

Hopefully this should fix it!

**Comment by pypingou** [comment]
Don't forget f24 as well :) (and that one goes through bodhi)

**Comment by cydrobolt** [comment]
@pypingou pushed update for f24 as well

**Comment by pypingou** [comment]
Thanks :)

The idea is that people should be able to go from N-1 (say f23) to N (say f24), so every package in N must be at a newer or equal version as the one in N-1.
