### ISSUE TITLE
Doesn't work with an ' in name

### ISSUE THREAD

**Issue by pranavk** [fedora-infra/mote#96]
Could not access a URL 

https://meetbot.fedoraproject.org/fedora-meeting/2016-04-15/apac_ambassador's_meeting.2016-04-15-05.04.log.html

Apparently, it has a ' in its name, which seems the most probable reason.

**Comment by cydrobolt** [comment]
Already fixed in 10f6ad97ddedc1b8ab5be2da6e795fed7063c396 but not yet deployed. I'll try to do that soon :)
