### ISSUE TITLE
No logs

### ISSUE THREAD

**Issue by puiterwijk** [fedora-infra/mote#97]
There are no logs in /var/log/httpd/error_log on 500's and no indication of where the logs are in the SOP.

Please add logging so server errors can be debugged.

**Comment by cydrobolt** [comment]
The httpd log file should contain logs; however, they should also be available if you run `service httpd status`

I'll check on this soon.

**Comment by puiterwijk** [comment]
service log:
May 11 01:15:08 value01.phx2.fedoraproject.org systemd[1]: Starting The Apache HTTP Server...
May 11 01:15:09 value01.phx2.fedoraproject.org httpd[28036]: [Wed May 11 01:15:09.053645 2016] [env:warn] [pid 28036] AH01506: PassEnv variable HOSTNAME was undefined
May 11 01:15:09 value01.phx2.fedoraproject.org systemd[1]: Started The Apache HTTP Server.

[root@value01 httpd][PROD]# cat error_log
[root@value01 httpd][PROD]# 


homepage:
500

Sorry, it seems like something went wrong.

If this was unexpected, please open a ticket on our issue tracker.



This has NOT been resolved. Please fix ASAP.

**Comment by cydrobolt** [comment]
Looks like the function server_error_500(e): in the mote init.py should be logging e to stderr.

**Comment by cydrobolt** [comment]
See #99 @puiterwijk

**Comment by puiterwijk** [comment]
Looks like this still isn't fixed.
Mote again threw 500 responses, with an empty error_log.

**Comment by cydrobolt** [comment]
We never pushed this update afaik. I'll try to build it and ping you.

**Comment by puiterwijk** [comment]
@cydrobolt Note that we are currently frozen, and value01 freezes...
Also, is there any specific reason this was never built and updated, as now we again crashed without having any idea as to why.

**Comment by cydrobolt** [comment]
I'm not sure why this was not built and updated. It's possible that it was lost in the mix. I can built it and package it, then we can deploy the fix once the freeze is over.

**Comment by cydrobolt** [comment]
I've built mote 0.6.1 on Koji: https://koji.fedoraproject.org/koji/taskinfo?taskID=18652391

**Comment by cydrobolt** [comment]
It's been deployed. Closing again.
